import React, { useEffect } from 'react';
import { motion } from 'framer-motion';
import Footer from '../components/layout/Footer';

const TERMS_SECTIONS = [
    {
        title: "Acceptance of Terms",
        content: "By accessing or using InterviewIQ, you agree to be bound by these Terms of Service. If you do not agree to all of the terms and conditions, you may not access the service."
    },
    {
        title: "Description of Service",
        content: "InterviewIQ provides an AI-powered mock interview platform, including but not limited to, adaptive questioning, live coding environments, and performance analytics."
    },
    {
        title: "User Accounts",
        content: "You must provide accurate and complete information when creating an account. You are solely responsible for the activity that occurs on your account and for keeping your account password secure."
    },
    {
        title: "Resume & Content Upload",
        content: "By uploading your resume or other content, you grant InterviewIQ the right to use, parse, and analyze this data solely for the purpose of providing and improving the service. We do not claim ownership of your content."
    },
    {
        title: "AI-Generated Content Disclaimer",
        content: "The feedback, scores, and questions generated by InterviewIQ are powered by artificial intelligence. While we strive for accuracy, AI-generated content may occasionally be inaccurate or inappropriate. You should verify critical information independently."
    },
    {
        title: "Code Execution Environment",
        content: "Our live coding environment is provided for educational and interview preparation purposes.",
        bullets: [
            "You agree not to use the sandbox for malicious activities.",
            "Attempting to breach, overload, or misuse the execution environment is strictly prohibited."
        ]
    },
    {
        title: "Acceptable Use Policy",
        content: "You agree not to use the Service to:",
        bullets: [
            "Violate any local, state, national, or international law.",
            "Interfere with or disrupt the servers or networks connected to the Service.",
            "Reproduce, duplicate, copy, sell, resell or exploit any portion of the Service without express written permission."
        ]
    },
    {
        title: "Data & Privacy",
        content: "Your privacy is important to us. Please review our Privacy Policy to understand how we collect, use, and protect your personal information and interview data."
    },
    {
        title: "Intellectual Property",
        content: "The Service and its original content (excluding User Content), features, and functionality are and will remain the exclusive property of InterviewIQ and its licensors."
    },
    {
        title: "Payment & Subscriptions",
        content: "Certain features may be subject to payment. By selecting a premium tier, you agree to pay the fees indicated. Subscriptions are billed in advance on a recurring basis and are non-refundable."
    },
    {
        title: "Service Availability",
        content: "We do not guarantee that our Service will be uninterrupted or error-free. We reserve the right to modify, suspend, or discontinue the Service at any time without notice."
    },
    {
        title: "Limitation of Liability",
        content: "In no event shall InterviewIQ, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service."
    },
    {
        title: "Termination",
        content: "We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms."
    },
    {
        title: "Changes to Terms",
        content: "We reserve the right, at our sole discretion, to modify or replace these Terms at any time. By continuing to access or use our Service after those revisions become effective, you agree to be bound by the revised terms."
    },
    {
        title: "Governing Law",
        content: "These Terms shall be governed and construed in accordance with the laws of the jurisdiction in which InterviewIQ operates, without regard to its conflict of law provisions."
    },
    {
        title: "Contact Information",
        content: "If you have any questions about these Terms, please contact us via our Contact Support page."
    }
];

export default function Terms() {
    useEffect(() => {
        window.scrollTo(0, 0);
    }, []);

    return (
        <div style={{
            minHeight: '100vh',
            display: 'flex',
            flexDirection: 'column',
            background: 'var(--bg-0)',
            position: 'relative',
            overflow: 'hidden',
        }}>
            {/* Subtle decorative background text */}
            <div style={{
                position: 'fixed',
                top: '5%',
                left: '50%',
                transform: 'translateX(-50%)',
                fontSize: '25vw',
                fontFamily: 'Outfit, sans-serif',
                fontWeight: 800,
                color: 'var(--text-0)',
                opacity: 0.02,
                pointerEvents: 'none',
                whiteSpace: 'nowrap',
                letterSpacing: '-0.05em',
            }}>
                LEGAL
            </div>

            <style>
                {`
                .terms-card {
                    position: relative;
                    z-index: 10;
                    max-width: 900px;
                    width: 100%;
                    background: var(--bg-1);
                    border-radius: 28px;
                    padding: 80px 70px;
                    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.04), 0 1px 3px rgba(0, 0, 0, 0.02);
                    border: 1px solid var(--border-md);
                    margin: 80px auto 120px;
                }
                
                @media (max-width: 900px) {
                    .terms-card {
                        padding: 50px 30px;
                        border-radius: 24px;
                        margin: 60px auto 80px;
                        width: calc(100% - 48px);
                    }
                }
                `}
            </style>

            <div style={{ flex: 1, display: 'flex', justifyContent: 'center' }}>
                <motion.div
                    className="terms-card"
                    initial={{ opacity: 0, y: 30 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.6, ease: [0.16, 1, 0.3, 1] }}
                >
                    {/* Header */}
                    <div style={{ marginBottom: 50, position: 'relative' }}>
                        {/* Decorative thin line */}
                        <div style={{
                            position: 'absolute',
                            left: -20,
                            top: 6,
                            bottom: 6,
                            width: 3,
                            background: 'var(--accent)',
                            borderRadius: 4,
                            opacity: 0.8,
                        }} />

                        <span style={{
                            fontFamily: 'Fira Code, monospace',
                            fontSize: 12,
                            fontWeight: 600,
                            letterSpacing: '0.15em',
                            color: 'var(--accent)',
                            textTransform: 'uppercase',
                            marginBottom: 12,
                            display: 'block'
                        }}>
                            AGREEMENT
                        </span>
                        <h1 style={{
                            fontFamily: 'Outfit, sans-serif',
                            fontSize: 'clamp(32px, 5vw, 42px)',
                            fontWeight: 700,
                            color: 'var(--text-0)',
                            letterSpacing: '-0.02em',
                            lineHeight: 1.1,
                            marginBottom: 16,
                        }}>
                            Terms of Service
                        </h1>
                        <p style={{
                            fontSize: 16,
                            color: 'var(--text-1)',
                            fontFamily: 'Manrope, sans-serif',
                            fontWeight: 500,
                            lineHeight: 1.5,
                        }}>
                            Effective Date: February 22, 2026
                        </p>
                    </div>

                    <div style={{ height: 1, background: 'var(--border)', marginBottom: 50 }} />

                    {/* Content */}
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 48 }}>
                        {TERMS_SECTIONS.map((section, index) => (
                            <section key={index}>
                                <h2 style={{
                                    fontFamily: 'Outfit, sans-serif',
                                    fontSize: 22,
                                    fontWeight: 700,
                                    color: 'var(--text-0)',
                                    marginBottom: 16,
                                    letterSpacing: '-0.01em',
                                    display: 'flex',
                                    alignItems: 'center',
                                    gap: 12,
                                }}>
                                    <span style={{
                                        color: 'var(--accent)',
                                        opacity: 0.8,
                                        fontSize: 20
                                    }}>
                                        {String(index + 1).padStart(2, '0')}.
                                    </span>
                                    {section.title}
                                </h2>
                                <p style={{
                                    fontFamily: 'Manrope, sans-serif',
                                    fontSize: 16,
                                    color: 'var(--text-1)',
                                    lineHeight: 1.7,
                                    paddingLeft: 35,
                                }}>
                                    {section.content}
                                </p>
                                {section.bullets && (
                                    <ul style={{
                                        marginTop: 16,
                                        paddingLeft: 35,
                                        listStyle: 'none',
                                        display: 'flex',
                                        flexDirection: 'column',
                                        gap: 12,
                                    }}>
                                        {section.bullets.map((bullet, i) => (
                                            <li key={i} style={{
                                                fontFamily: 'Manrope, sans-serif',
                                                fontSize: 16,
                                                color: 'var(--text-1)',
                                                lineHeight: 1.6,
                                                display: 'flex',
                                                position: 'relative',
                                            }}>
                                                <div style={{
                                                    position: 'absolute',
                                                    left: -20,
                                                    top: 10,
                                                    width: 6,
                                                    height: 6,
                                                    borderRadius: '50%',
                                                    background: 'var(--accent)',
                                                    opacity: 0.6,
                                                }} />
                                                {bullet}
                                            </li>
                                        ))}
                                    </ul>
                                )}
                            </section>
                        ))}
                    </div>
                </motion.div>
            </div>

            <Footer style={{ position: 'relative', zIndex: 10 }} />
        </div>
    );
}
